/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jimbogies (https://sketchfab.com/jimbogies)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gallery-showroom-22b427f9480d4e31b9bfe26f19b746e1
Title: Gallery Showroom
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Buildingb(props) {
  const { nodes, materials } = useGLTF('/buildingb.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0,15,0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials.Wood02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.Wood01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.Diffuse}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_1.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_3.geometry}
          material={materials.Plaster}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_2.geometry}
          material={materials.Clear}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_3.geometry}
          material={materials.Ceiling}
        />
        <lineSegments
          geometry={nodes.Material2_4.geometry}
          material={materials.edge_color13900255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_4.geometry}
          material={materials.Light}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_5.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_6.geometry}
          material={materials.Metal04}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_15.geometry}
          material={materials.Flourescent}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/buildingb.gltf')
